source "https://rubygems.org"

gem 'feedjira'
gem 'httparty' # wanted by feedjira
gem 'colorize'
gem "feedbag" # Autodiscovery of RSSs :)

gem 'news-api' # https://newsapi.org/docs/client-libraries/ruby
