
crawl:
	ruby crawl.rb | tee sample-crawl-output.txt

feedbag-test:
	ruby feedbag-test.rb

newsapi-test:
	./news-api-test.sh 'Trump%20vs%20Biden'
# empty ./news-api-test.sh 'Riccardo%20Carlesso'

clean-articles:
	rm out/* out/*/*
